name: Matrix workflow
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [12,13,14]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
            - name: cache code
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ hashFiles('**/package-lock.json')}}
            - name: Install Dependencies
              uses: npm ci
            - name: Build code
              uses: npm run build
             

            

